### ISSUE TITLE
Rename to ory/events or ory/summit :)

### ISSUE THREAD

**Issue by aeneasr** [ory/summit-platform#12]
nitpick, but `ory/ory-events` is kinda duplicated. can we rename to `ory/events` (events might be misleading as in event bus) or `ory/summit`?

**Comment by vinckr** [comment]
good point yes, ory summit should be good! 
but I cant rename it apparently, the "settings" option is gone.
you probably need to add me again as maintainer here @aeneasr

**Comment by aeneasr** [comment]
done
